random_state = 0
sub_cohort = 'all'
scale_transform = true
pca = false

[stats]
pvalue_thresh = 0.05
power = 0.95
alpha = 0.05

[feature_selection]
multisurf_cross_validation_splits = 50
cross_validation_splits = 2
cross_validation_repeats = 25
number_of_mi_features = 0.035
number_of_features = 30

[feature_selection.addition]
method = "feature_importance"
importance_selection = 'shap'

[augmentation.smote]
new_cancer_ratio = 0.5
new_total_samples = 0

[optimization.optuna]
scorer = ['mcc', 'sens@99spec']
trials = 300
before_feature_selection = false
after_rfa = true
before_validation = false
