[flake8]
# Consistent with black formatter
max-line-length = 119
exclude = venv,tests,.history,Results,

max-doc-length = 119

# Rules to ignore
ignore =
    # Docstrings in modules
    D100, D104,
    # Imperative mood initial word
    D401,
    # Line break before binary operator
    W503,
    # Missing docstring in __init__
    D107, D105,
    # Don't have to end with a period
    D400,
    # Whitespace before ':', clashes with black
    E203,
    # Formatting belongs to black
    E704,
    # Single letter variable names like 'X' are not allowed
    VNE001,
    # Argument name 'X' should be lowercase
    N803, N806,

per-file-ignores =
    main.py:U100, E501,
    src/features/__init__.py:F401
    src/features/preprocessing.py:F401
    missingpy/missforest.py:U100
    src/data_loader.py:U100
    src/features/optimisation.py:U100
    src/features/features.py:U100
    src/features/shap.py:D205
